/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/core/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/auth/jwks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SuppliersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/suppliers/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuppliersController_current"];
        put: operations["SuppliersController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/v1/core/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_memberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["UsersController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_consents"];
        put?: never;
        post: operations["UsersController_consent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_subscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_access"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_read"];
        trace?: never;
    };
    "/api/v1/core/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RegistryController_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_list"];
        put?: never;
        post: operations["MediaController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/media/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/catalogs/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogsController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/core/catalogs/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogsController_locations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PresenceController_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/profile/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PresenceController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/profile/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PresenceController_unpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/public/{slug}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PresenceController_share"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PresenceController_current"];
        put: operations["PresenceController_save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/public/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PresenceController_publicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/collections/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentController_list"];
        put?: never;
        post: operations["ContentController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/collections/{collection}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentController_reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/collections/{collection}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ContentController_get"];
        put: operations["ContentController_update"];
        post?: never;
        delete: operations["ContentController_archive"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/collections/{collection}/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/collections/{collection}/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentController_unpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/collections/{collection}/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContentController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/public/{slug}/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicContentController_media"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/public/{slug}/collections/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicContentController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presence/public/{slug}/collections/{collection}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicContentController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/public/{supplierId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LeadsController_capture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LeadsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/{id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["LeadsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            email: string;
            password: string;
            displayName: string;
        };
        TokensDto: {
            accessToken: string;
            refreshToken: string;
            expiresIn: number;
            tokenType: string;
        };
        LoginDto: {
            email: string;
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        SupplierDto: {
            contactEmail?: string | null;
            contactPhone?: string | null;
            categoryId?: string;
            locationId?: string;
            businessName: string;
            category: string;
            city: string;
            serviceAreas?: string[];
            acceptInquiries?: Record<string, never>;
        };
        SupplierResponseDto: {
            contactEmail: string | null;
            contactPhone: string | null;
            categoryId: string | null;
            locationId: string | null;
            id: string;
            organizationId: string;
            businessName: string;
            category: string;
            city: string;
            serviceAreas: string[];
            acceptInquiries: boolean;
        };
        PreferencesDto: {
            email: boolean;
            push: boolean;
        };
        MeDto: {
            id: string;
            email: string;
            displayName: string;
            locale: string;
            timezone: string;
            notificationPreferences: components["schemas"]["PreferencesDto"];
        };
        ProfileDto: {
            displayName?: string;
            /** @enum {string} */
            locale?: "en" | "ar" | "fr";
            timezone?: string;
            notificationPreferences?: components["schemas"]["PreferencesDto"];
        };
        OrganizationNameDto: {
            name: string;
        };
        MembershipDto: {
            organizationId: string;
            /** @enum {string} */
            role: "OWNER" | "EDITOR" | "VIEWER";
            organization: components["schemas"]["OrganizationNameDto"];
        };
        Object: Record<string, never>;
        SessionDto: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ConsentResponseDto: {
            /** @enum {string} */
            purpose: "marketing" | "analytics";
            version: string;
            granted: boolean;
            id: string;
            userId: string;
            /** Format: date-time */
            recordedAt: string;
        };
        ConsentDto: {
            /** @enum {string} */
            purpose: "marketing" | "analytics";
            version: string;
            granted: boolean;
        };
        SubscriptionDto: {
            id: string;
            planCode: string;
            status: string;
            features: string[];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            cancelAtPeriodEnd: boolean;
        };
        AccessDto: {
            userId: string;
            features: string[];
        };
        NotificationDto: {
            id: string;
            userId: string;
            kind: string;
            title: string;
            body: string;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        HealthDto: {
            status: string;
            edition: string;
        };
        ModuleDto: {
            id: string;
            implemented: boolean;
            enabled: boolean;
        };
        MediaResponseDto: {
            id: string;
            width: number;
            height: number;
            bytes: number;
            /** @enum {string} */
            mimeType: "image/webp";
            /** @enum {string} */
            status: "READY";
        };
        CatalogResponseDto: {
            id: string;
            /** @enum {string} */
            kind: "CATEGORY" | "LOCATION";
            label: string;
            active: boolean;
        };
        ReadinessDto: {
            ready: boolean;
            missing: string[];
            score: number;
        };
        VersionDto: {
            version: number;
        };
        SocialLinkDto: {
            /** @enum {string} */
            provider: "WEBSITE" | "INSTAGRAM" | "FACEBOOK" | "TIKTOK" | "YOUTUBE" | "LINKEDIN";
            url: string;
        };
        OpeningHourDto: {
            weekday: number;
            closed: boolean;
            opens?: string;
            closes?: string;
        };
        PresenceResponseDto: {
            showEmail?: boolean;
            showPhone?: boolean;
            slug: string;
            description: string;
            published: boolean;
            tagline?: string;
            logoMediaId?: string | null;
            coverMediaId?: string | null;
            seoTitle?: string;
            seoDescription?: string;
            accentColor?: string;
            socialLinks?: components["schemas"]["SocialLinkDto"][];
            openingHours?: components["schemas"]["OpeningHourDto"][];
            sections?: string[];
            version: number;
            id: string;
            supplierId: string;
            publishedAt: string | null;
        };
        ShareDto: {
            url: string;
            qrPayload: string;
            title: string;
            description: string;
        };
        PresenceDto: {
            showEmail?: boolean;
            showPhone?: boolean;
            slug: string;
            description: string;
            published: boolean;
            tagline?: string;
            logoMediaId?: string | null;
            coverMediaId?: string | null;
            seoTitle?: string;
            seoDescription?: string;
            accentColor?: string;
            socialLinks?: components["schemas"]["SocialLinkDto"][];
            openingHours?: components["schemas"]["OpeningHourDto"][];
            sections?: string[];
            version?: number;
        };
        PublicSupplierDto: {
            contactEmail?: string;
            contactPhone?: string;
            id: string;
            businessName: string;
            category: string;
            city: string;
            serviceAreas: string[];
        };
        MediaReferenceDto: {
            mediaId: string;
            /** @enum {string} */
            role: "COVER" | "GALLERY";
            altText: string;
            caption?: string;
        };
        PublicContentDto: {
            id: string;
            title: string;
            summary: string;
            description: string;
            categoryId: string | null;
            locationId: string | null;
            occurredAt: string | null;
            /** @enum {string|null} */
            type: "SERVICE" | "PRODUCT" | "PACKAGE" | "OFFER" | null;
            /** @enum {string|null} */
            pricingMode: "FIXED" | "FROM" | "ON_REQUEST" | "FREE" | null;
            amountMinor: number | null;
            currency: string | null;
            validFrom: string | null;
            validUntil: string | null;
            serviceAreas: string[];
            availabilityNote: string;
            featured: boolean;
            displayOrder: number;
            media: components["schemas"]["MediaReferenceDto"][];
        };
        PublicPresenceDto: {
            slug: string;
            description: string;
            supplier: components["schemas"]["PublicSupplierDto"];
            tagline: string;
            logoMediaId: string | null;
            coverMediaId: string | null;
            seoTitle: string;
            seoDescription: string;
            accentColor: string;
            socialLinks: components["schemas"]["SocialLinkDto"][];
            openingHours: components["schemas"]["OpeningHourDto"][];
            sections: string[];
            inquiriesEnabled: boolean;
            /** @description API-relative Leads capture path, or null. */
            inquiryPath: Record<string, never> | null;
            portfolio: components["schemas"]["PublicContentDto"][];
            listings: components["schemas"]["PublicContentDto"][];
            gallery: components["schemas"]["PublicContentDto"][];
        };
        ContentResponseDto: {
            id: string;
            title: string;
            summary: string;
            description: string;
            categoryId: string | null;
            locationId: string | null;
            occurredAt: string | null;
            /** @enum {string|null} */
            type: "SERVICE" | "PRODUCT" | "PACKAGE" | "OFFER" | null;
            /** @enum {string|null} */
            pricingMode: "FIXED" | "FROM" | "ON_REQUEST" | "FREE" | null;
            amountMinor: number | null;
            currency: string | null;
            validFrom: string | null;
            validUntil: string | null;
            serviceAreas: string[];
            availabilityNote: string;
            featured: boolean;
            displayOrder: number;
            media: components["schemas"]["MediaReferenceDto"][];
            supplierId: string;
            /** @enum {string} */
            kind: "PORTFOLIO" | "LISTING" | "GALLERY";
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "UNPUBLISHED" | "ARCHIVED";
            version: number;
            createdAt: string;
            updatedAt: string;
            publishedAt: string | null;
        };
        ContentWriteDto: {
            title: string;
            summary?: Record<string, never>;
            description?: Record<string, never>;
            categoryId?: string | null;
            locationId?: string | null;
            occurredAt?: string | null;
            /** @enum {string} */
            type?: "SERVICE" | "PRODUCT" | "PACKAGE" | "OFFER";
            /** @enum {string} */
            pricingMode?: "FIXED" | "FROM" | "ON_REQUEST" | "FREE";
            amountMinor?: number | null;
            currency?: string | null;
            validFrom?: string | null;
            validUntil?: string | null;
            serviceAreas?: string[];
            availabilityNote?: Record<string, never>;
            featured?: Record<string, never>;
            media: components["schemas"]["MediaReferenceDto"][];
            /** @description Required when updating an existing record; stale versions return 409. */
            version?: number;
        };
        ReorderDto: {
            ids: string[];
            /** @description Current profile version; returned by GET profile. */
            version: number;
        };
        LeadDto: {
            name: string;
            email?: string;
            phone?: string;
            message: string;
            /** @enum {string} */
            source: "DIRECT" | "QR" | "PROFILE" | "LISTING" | "SOCIAL" | "ADS" | "EMAIL";
            campaign?: string;
            contactConsent: boolean;
            contactConsentVersion: string;
        };
        ReceiptDto: {
            id: string;
        };
        LeadResponseDto: {
            id: string;
            supplierId: string;
            organizationId: string;
            /** @enum {string} */
            stage: "NEW" | "HOT" | "FOLLOW_UP" | "QUALIFIED" | "WON" | "LOST";
            name: string;
            email: string | null;
            phone: string | null;
            message: string;
            /** @enum {string} */
            source: "DIRECT" | "QR" | "PROFILE" | "LISTING" | "SOCIAL" | "ADS" | "EMAIL";
            campaign: string | null;
            contactConsent: boolean;
            contactConsentVersion: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StageDto: {
            /** @enum {string} */
            stage: "NEW" | "HOT" | "FOLLOW_UP" | "QUALIFIED" | "WON" | "LOST";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuppliersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponseDto"];
                };
            };
        };
    };
    SuppliersController_current: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponseDto"];
                };
            };
        };
    };
    SuppliersController_update: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponseDto"];
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    UsersController_memberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipDto"][];
                };
            };
        };
    };
    UsersController_sessions: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"][];
                };
            };
        };
    };
    UsersController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_consents: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponseDto"][];
                };
            };
        };
    };
    UsersController_consent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponseDto"];
                };
            };
        };
    };
    UsersController_subscriptions: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDto"][];
                };
            };
        };
    };
    UsersController_access: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessDto"];
                };
            };
        };
    };
    UsersController_notifications: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationDto"][];
                };
            };
        };
    };
    UsersController_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RegistryController_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleDto"][];
                };
            };
        };
    };
    MediaController_list: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
            };
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponseDto"][];
                };
            };
        };
    };
    MediaController_upload: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponseDto"];
                };
            };
        };
    };
    MediaController_file: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    CatalogsController_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponseDto"][];
                };
            };
        };
    };
    CatalogsController_locations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponseDto"][];
                };
            };
        };
    };
    PresenceController_readiness: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessDto"];
                };
            };
        };
    };
    PresenceController_publish: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresenceResponseDto"];
                };
            };
        };
    };
    PresenceController_unpublish: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresenceResponseDto"];
                };
            };
        };
    };
    PresenceController_share: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareDto"];
                };
            };
        };
    };
    PresenceController_current: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresenceResponseDto"];
                };
            };
        };
    };
    PresenceController_save: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresenceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresenceResponseDto"];
                };
            };
        };
    };
    PresenceController_publicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicPresenceDto"];
                };
            };
        };
    };
    ContentController_list: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
                type?: "SERVICE" | "PRODUCT" | "PACKAGE" | "OFFER";
            };
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"][];
                };
            };
        };
    };
    ContentController_create: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentWriteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"];
                };
            };
        };
    };
    ContentController_reorder: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDto"];
                };
            };
        };
    };
    ContentController_get: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"];
                };
            };
        };
    };
    ContentController_update: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentWriteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"];
                };
            };
        };
    };
    ContentController_archive: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"];
                };
            };
        };
    };
    ContentController_publish: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"];
                };
            };
        };
    };
    ContentController_unpublish: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"];
                };
            };
        };
    };
    ContentController_restore: {
        parameters: {
            query?: never;
            header: {
                "X-Organization-Id": string;
                "x-organization-id": string;
            };
            path: {
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponseDto"];
                };
            };
        };
    };
    PublicContentController_media: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    PublicContentController_list: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
                type?: "SERVICE" | "PRODUCT" | "PACKAGE" | "OFFER";
            };
            header?: never;
            path: {
                slug: string;
                collection: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicContentDto"][];
                };
            };
        };
    };
    PublicContentController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                collection: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicContentDto"];
                };
            };
        };
    };
    LeadsController_capture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplierId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptDto"];
                };
            };
        };
    };
    LeadsController_list: {
        parameters: {
            query?: {
                limit?: components["schemas"]["Object"];
                cursor?: string;
            };
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Pass as cursor to retrieve the next page. Absent on the last page. */
                    "X-Next-Cursor"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponseDto"][];
                };
            };
        };
    };
    LeadsController_update: {
        parameters: {
            query?: never;
            header: {
                "x-organization-id": string;
                "X-Organization-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadResponseDto"];
                };
            };
        };
    };
}
